In [ ]:
import pandas as pd
import numpy as np
import gensim
from sklearn.linear_model import LogisticRegression
from gensim.models.doc2vec import TaggedDocument
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.multiclass import OneVsRestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics
from sklearn.svm import SVC
from tqdm import tqdm
tqdm.pandas(desc="progress-bar")
from gensim.models import Doc2Vec
import multiprocessing
from sklearn import utils
from sklearn.model_selection import train_test_split
from gensim.parsing.preprocessing import remove_stopwords
from gensim.utils import simple_preprocess
from gensim.parsing.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
import re
import nltk
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

jdDataSet = pd.read_excel('jd_dataset_new.xlsx')
jdDataSet['cleaned_jd'] = ''
jdDataSet.head()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

,title,description,skills,cleaned_jd
0,ux designer,Our client is seeking a UI/UX Designer. Loca...,"CSS, Development, HTML, HTTP, JavaScript, Mana...",
1,ux designer,Position Description:Wipro Digital is seeking ...,UX Designing,
2,ux designer,HIGreetings from Data inc!!! Hope you are doin...,"""ui designer"" , ""user interface designer"" , ""v...",
3,ux designer,Our team is looking for an experienced UI/UX D...,"HTML 5, CSS3, jQuery, php, bootstrap, Angular",
4,ux designer,"Hi, Please send me your updated resume on raje...",UX Designer,

In [ ]:
print ("Displaying the distinct categories of jd -")
print (jdDataSet['title'].unique())

Displaying the distinct categories of jd -
['ux designer' 'infrastructure engineer' 'systems administrator'
 'ui developer' 'node .js developer' 'network engineer'
 'big data architect' 'android developer' 'salesforce developer'
 'ruby on rails developer' 'testing' 'network security administrator'
 'swift developer' 'application developer' 'data security analyst'
 'network support' 'technical support' 'data warehousing developer'
 'cloud architect' 'cloud infrastructure engineer' 'ios developer'
 'automation engineer' 'sql developer' 'qa engineer' 'telecom engineer'
 'php developer' 'site reliability engineer' 'hadoop developer'
 'aws architect' 'business analyst' 'data analyst' 'project manager'
 'technology analyst' 'java developer' 'devops engineer'
 'front end developer' 'back end developer' 'full stack developer'
 'software engineer' 'product manager' 'java engineer' '.net developer'
 'web developer' 'c# developer' 'c developer' 'c++ developer'
 'system engineer' 'database engineer' 'data scientist' 'data engineer']

In [ ]:
def clean(text):
    text = re.sub('http\S+\s*', ' ', text)  # remove URLs
    text = re.sub('RT|cc', ' ', text)  # remove RT and cc
    text = re.sub('#\S+', '', text)  # remove hashtags
    text = re.sub('@\S+', '  ', text)  # remove mentions
    text = re.sub('[%s]' % re.escape("""!"$%&'()*,-/:;<=>?@[\]^_`{|}~"""), ' ', text)  # remove punctuations
    text = re.sub(r'[^\x00-\x7f]',r' ', text) 
    text = re.sub('\s+', ' ', text)  # remove extra whitespace
    return text

In [ ]:
def extractNoun(wordsList):
  tagged = nltk.pos_tag(wordsList)
  filtered_pos = []
  for one in tagged:
    if one[1] == 'NN' or one[1] == 'NNS' or one[1] == 'NNP' or one[1] == 'NNPS':
      filtered_pos.append(one[0])
  return filtered_pos

In [ ]:
#cleaning data
jdDataSet['cleaned_jd'] = jdDataSet.description.apply(lambda x: clean(x))

# Removing the stop words
jdDataSet['cleaned_jd'] = jdDataSet.cleaned_jd.apply(lambda x: remove_stopwords(x))

# Tokenize the text column
jdDataSet['cleaned_jd'] = [simple_preprocess(line, deacc=True) for line in jdDataSet['cleaned_jd']] 

# Get the stemmed_tokens
porter_stemmer = PorterStemmer()
jdDataSet['cleaned_jd'] = [[porter_stemmer.stem(word) for word in tokens] for tokens in jdDataSet['cleaned_jd'] ]

# get the lammatized tokens
# lemmatizer = WordNetLemmatizer() 
# jdDataSet['cleaned_jd'] = [[lemmatizer.lemmatize(word) for word in tokens] for tokens in jdDataSet['cleaned_jd'] ]

# extract only noun 
jdDataSet['cleaned_jd'] = jdDataSet.cleaned_jd.apply(lambda x: extractNoun(x))

jdDataSet['cleaned_jd']

0       [client, seek, design, locat, bethesda, md, po...
1       [posit, descript, digit, seek, design, deliv, ...
2       [higreet, data, financi, client, design, role,...
3       [team, look, design, basi, resid, francisco, b...
4       [hi, plea, resum, interest, posit, design, loc...
                              ...
2495    [plea, email, resum, shveta, lead, sr, data, e...
2496            [need, data, expertis, sql, python, hive]
2497    [bach, degre, posit, plea, resum, word, format...
2498    [titl, data, boston, madur, competit, doe, can...
2499    [data, engineerjob, data, support, quantit, en...
Name: cleaned_jd, Length: 2500, dtype: object

In [ ]:
# to generate N grams
def generate_N_grams(text,ngram=1):
    temp=zip(*[text[i:] for i in range(0,ngram)])
    ans=[' '.join(ngram) for ngram in temp]
    return ans

# jdDataSet['cleaned_jd'] = jdDataSet.cleaned_jd.apply(lambda x: x + generate_N_grams(list(x),3))

# jdDataSet['cleaned_jd'][0]

In [ ]:
# to do classification only skilss
def extractSkills(string):
    if isinstance(string,float):
        return [" "," "]
    lst = string.split(',')
    lst = [s.strip() for s in lst]
    return lst

jdDataSet['cleaned_jd'] += jdDataSet.skills.apply(lambda x: list(extractSkills(x)) + list(extractSkills(x)))

jdDataSet['cleaned_jd'][2]

['higreet',
 'data',
 'financi',
 'client',
 'design',
 'role',
 'york',
 'york',
 'locat',
 'client',
 'plea',
 'job',
 'let',
 'posit',
 'plea',
 'resum',
 'rsrivastava',
 'directli',
 'phone',
 'role',
 'design',
 'york',
 'york',
 'durat',
 'year',
 'contract',
 'job',
 'design',
 'collabor',
 'user',
 'lead',
 'project',
 'team',
 'conceptu',
 'design',
 'goal',
 'friction',
 'satisfact',
 'posit',
 'sit',
 'remit',
 'includ',
 'design',
 'session',
 'ensur',
 'deliv',
 'experi',
 'possibl',
 'thi',
 'includ',
 'clickabl',
 'prototyp',
 'champion',
 'challeng',
 'design',
 'test',
 'multipl',
 'compet',
 'freedom',
 'tool',
 'work',
 'design',
 'kei',
 'promot',
 'class',
 'execut',
 'transform',
 'custom',
 'design',
 'point',
 'relev',
 'user',
 'moment',
 'experi',
 'design',
 'knowledg',
 'softwar',
 'craft',
 'team',
 'collabor',
 'empath',
 'consum',
 'product',
 'contributor',
 'agil',
 'process',
 'ideal',
 'abl',
 'design',
 'concept',
 'post',
 'sketch',
 'fidel',
 'design',
 'problem',
 'solv',
 'cross',
 'platform',
 'cross',
 'devic',
 'scenario',
 'collabor',
 'lead',
 'creat',
 'asset',
 'test',
 'releas',
 'design',
 'product',
 'environ',
 'understand',
 'digit',
 'design',
 'framework',
 'method',
 'goal',
 'user',
 'assist',
 'synthes',
 'test',
 'take',
 'ownership',
 'synthes',
 'design',
 'feedback',
 'product',
 'stake',
 'holder',
 'goal',
 'minim',
 'product',
 'offer',
 'opinion',
 'design',
 'challeng',
 'expo',
 'design',
 'debt',
 'incur',
 'collabor',
 'cross',
 'function',
 'product',
 'team',
 'inspir',
 'methodolog',
 'requir',
 'skill',
 'design',
 'tool',
 'adob',
 'xd',
 'adob',
 'creativ',
 'suit',
 'sketch',
 'omnigraffl',
 'axur',
 'profici',
 'prototyp',
 'design',
 'tool',
 'axur',
 'adob',
 'xd',
 'profici',
 'diagram',
 'tool',
 'skill',
 'html',
 'cs',
 'j',
 'goal',
 'optim',
 'end',
 'engin',
 'profici',
 'creat',
 'reusabl',
 'pattern',
 'promot',
 'year',
 'design',
 'mobil',
 'portfolio',
 'respons',
 'bachelor',
 'degre',
 'design',
 'design',
 'field',
 'highli',
 'desir',
 'rahul',
 'srivastavadata',
 'summit',
 'avenuemontval',
 'email',
 'rsrivastava',
 '"ui designer"',
 '"user interface designer"',
 '"visual designer"',
 '"graphics designer"',
 'Adobe',
 '"Creative Suite"',
 'Sketch',
 'Omnigraffle',
 'Axure',
 'Prototype',
 'Prototyping',
 'html',
 'css',
 '"responsive web"',
 '"ui designer"',
 '"user interface designer"',
 '"visual designer"',
 '"graphics designer"',
 'Adobe',
 '"Creative Suite"',
 'Sketch',
 'Omnigraffle',
 'Axure',
 'Prototype',
 'Prototyping',
 'html',
 'css',
 '"responsive web"']

In [ ]:
train, test = train_test_split(jdDataSet, test_size=0.3, random_state=40)

train_tagged = train.apply( lambda r: TaggedDocument(words=r['cleaned_jd'], tags=[r.title]), axis=1)
test_tagged = test.apply( lambda r: TaggedDocument(words=r['cleaned_jd'], tags=[r.title]), axis=1)

train

,title,description,skills,cleaned_jd
644,swift developer,As a team member of the BESS/SWIFT Application...,swift,"[team, member, support, group, respons, suppor..."
847,technical support,GoAhead Solutions has an immediate need for a ...,"Desktop Support Analyst, Mac iOS, Windows OS, ...","[solut, immedi, support, analyst, thi, month, ..."
1280,php developer,PHP Developer (Front-end) A exiting growing co...,"PHP, jQuery, , Front-end Development, Back-end...","[php, end, exit, grow, compani, look, php, end..."
2280,c++ developer,"Synechron, a recognized leader and expert in b...",C++ Developer,"[synechron, recogn, leader, expert, valu, fina..."
1778,front end developer,Sr.Front End Developer Modis is looking for a ...,Sr.Front End Developer,"[sr, end, develop, look, sr, end, develop, joi..."
...,...,...,...,...
1863,full stack developer,Apex is seeking a Java/J2EE Software Engineer ...,GWT Hibernate Oracle SQL Java J2EE,"[apex, seek, java, engin, googl, toolkit, gwt,..."
1330,site reliability engineer,"The SRE team works on coding, automating, and ...","API, Data Warehouse, Hadoop, Linux, Management...","[sre, team, work, code, avail, reliabl, perfor..."
2213,c developer,SCOPE OF SERVICES:A CMS developer will be resp...,"CMS, Java, Teamsite","[scope, cm, respons, design, code, supervis, p..."
2055,.net developer,The Senior Developer will work closely with th...,.net; c#; asp.net; mvc; RESTful; WebAPI's; SQL...,"[develop, work, team, busi, analyst, featur, e..."
2267,c++ developer,*NO THIRD PARTY RESUMES* U.S. Citizens and tho...,"C++, Java, or C#, UNIX","[pa, resum, citizen, author, work, time, role,..."

In [ ]:
test

,title,description,skills,cleaned_jd
2383,database engineer,"Role: Database EngineerLocation: Palo Alto, CA...","Apache Storm, Java, Linux","[role, databas, palo, month, contract, product..."
1297,php developer,"PHP Developer Location: Atlanta, GASalary Rang...","PHP, CakePHP, Laravel, HTML5, CSS3, JQuery, An...","[php, atlanta, gasalari, rang, time, hire, pos..."
2,ux designer,HIGreetings from Data inc!!! Hope you are doin...,"""ui designer"" , ""user interface designer"" , ""v...","[higreet, data, financi, client, design, role,..."
1647,technology analyst,Infosys Digital Experience Technology Analyst ...,"Drupal 7.x,PHP, Programmer","[digit, experi, technolog, analyst, php, houst..."
1356,hadoop developer,"Dear Candidate,For our client, a major company...",Big Data Hadoop Hive Pig MapReduce Spark Scala...,"[dear, candid, client, compani, look, job, tit..."
...,...,...,...,...
1931,software engineer,Client: Xavient/ Sling TVLocation: American Fo...,10 years of professional enterprise and Postgr...,"[client, xavient, fork, month, cth, posit, eng..."
649,swift developer,As a team member of the BESS/SWIFT Application...,swift,"[team, member, support, group, respons, suppor..."
293,network engineer,Duties and ResponsibilitiesIn this F5 Load Bal...,"IP Routing (BGP & OSPF), SSL Termination; Ethe...","[duti, load, balanc, engin, posit, opportun, w..."
502,testing,"Role: AB TestingLocation: San Bruno, CAFull T...","A/B, MVT tests, Retail, ecommerce","[role, ab, testingloc, bruno, monitor, test, d..."
98,infrastructure engineer,Infrastructure/Systems EngineerPermanent salar...,"Windows, SCCM, WSUS, iOS, Android, Cisco, SAN,...","[infrastructur, system, career, corpor, il, ma..."

In [ ]:
VECTOR_SIZE = 325
WINDOW=15
EPOCHS=25

model_dbow = Doc2Vec(dm=0, vector_size=VECTOR_SIZE, negative=5, window=WINDOW, min_count=2, workers=5,alpha=0.065, min_alpha=0.065)
model_dbow.build_vocab([x for x in tqdm(train_tagged.values)])
model_dbow['java developer']

100%|██████████| 1750/1750 [00:00<00:00, 1152643.22it/s]

array([ 1.09508634e-03, -9.99043114e-04, -1.40982948e-03,  1.01702299e-03,
       -1.34742225e-03,  3.46650981e-04, -9.76681942e-04, -1.29472546e-03,
        3.19541490e-04, -6.00111904e-04, -1.25116564e-03,  9.16030083e-04,
        5.00785536e-04, -4.17109040e-05,  1.05728721e-03,  1.29475899e-03,
       -3.56334349e-04,  4.27599181e-04, -1.37083873e-04, -4.47143277e-04,
        9.75307310e-04,  5.91649383e-04, -6.27902627e-04,  1.10720990e-04,
       -3.17252154e-04, -5.73740690e-04, -2.77411018e-04,  3.53940486e-05,
        1.52599229e-03, -2.20748028e-04, -4.24007121e-05,  1.48570968e-03,
       -1.07828912e-03,  1.18288444e-03,  9.67030239e-04, -6.85255218e-04,
        1.81108844e-05, -1.01012771e-03,  1.33508048e-03, -6.66123815e-04,
        3.09068593e-04, -7.18840107e-04,  4.77733469e-04, -4.68895683e-04,
       -1.47065695e-03,  6.32423442e-04, -4.32128058e-04, -1.66316706e-04,
        6.80078694e-04,  1.44644745e-03, -1.01148756e-03,  1.28054875e-03,
       -1.08876626e-03,  2.29444558e-04, -3.32801341e-04,  1.26171159e-03,
        1.06057420e-03, -6.55825192e-04,  8.94056691e-04, -3.75173549e-04,
        7.06524006e-05, -6.43101579e-04, -7.82490708e-04,  8.23263486e-04,
       -5.57261847e-05, -1.13791076e-03,  3.35326622e-04, -2.08236470e-05,
       -2.49211065e-04, -7.49088475e-04,  6.76835713e-04, -1.50177733e-03,
       -1.98373556e-04, -4.72690095e-04, -3.55235592e-04, -7.31739201e-05,
       -1.14801514e-04,  1.18643220e-03,  1.34796559e-04, -7.59311253e-04,
       -1.41668064e-03, -5.47543867e-04, -5.00917202e-04,  1.24251563e-03,
       -4.57434799e-04, -1.29697961e-03,  6.68821391e-04,  1.35469390e-03,
       -7.66464393e-04, -1.18325267e-03, -1.49429927e-03,  1.28100932e-04,
        5.68497751e-04, -8.24848481e-04,  9.62065416e-04, -7.71746971e-04,
       -1.17137446e-03, -1.31090335e-03, -1.27279572e-03, -1.20069145e-03,
       -4.07266998e-05, -4.75372712e-04,  7.62080599e-04,  3.28461872e-04,
       -1.32634398e-03, -7.60015857e-04, -7.17273360e-05,  8.87844919e-07,
       -1.46646227e-03, -6.97437936e-05,  6.65050175e-04,  3.51474242e-04,
        5.06093311e-05,  1.07604195e-03, -1.32619147e-03,  1.06531952e-03,
       -1.05414714e-03, -5.95256279e-04, -9.61437589e-04,  7.00452190e-04,
       -1.08742726e-03,  1.27960485e-03,  1.52712129e-03,  5.92972385e-04,
        1.70043626e-04,  1.47575827e-03,  1.93763350e-04,  2.95339385e-04,
       -1.03767740e-03, -1.01798447e-03,  2.55816267e-04, -3.44116677e-04,
       -1.07633381e-03, -1.13349082e-03,  9.41389357e-04, -9.72578593e-04,
       -5.06607059e-04,  8.89034418e-05,  2.84263282e-04, -2.49632139e-04,
       -1.19773613e-03, -6.99127442e-04, -4.84956428e-04,  1.36878330e-03,
       -6.16998412e-04, -4.95009823e-04,  4.67710488e-04, -2.05630698e-04,
        6.89043140e-04,  7.72044354e-04, -9.50752117e-04, -7.53550194e-05,
        6.77070406e-04, -6.30463546e-05,  4.30713786e-04, -4.81189112e-04,
        4.46347294e-05,  2.36716733e-04, -1.45410479e-03, -2.41947433e-04,
        8.35446233e-04, -1.39973138e-03,  1.09075638e-03,  6.97959913e-04,
        1.51275354e-03, -1.39276369e-03, -1.23783515e-03, -6.23112021e-04,
       -3.71029513e-04, -7.44592049e-04, -1.44203985e-03,  1.17148960e-03,
       -8.33580620e-04,  6.91137859e-04,  6.62104343e-04, -8.46035604e-04,
       -6.89074805e-04, -4.39974712e-04, -1.52393346e-04, -1.12558494e-03,
        5.42945287e-04, -1.10090349e-03,  2.86519207e-04, -6.00124849e-06,
        9.19981801e-04,  5.18739806e-04, -1.16181327e-03,  8.45807022e-04,
        7.60483148e-04,  1.38554862e-03,  9.85032530e-04, -1.47277009e-04,
       -9.42798972e-04, -4.22959652e-04,  4.11603542e-04,  9.38567609e-05,
        9.27790243e-04, -1.17468764e-03, -1.96620560e-04,  1.50553742e-03,
        1.14710140e-03,  5.71109995e-04, -6.38062891e-04,  1.29485445e-03,
        1.25933799e-03, -1.19605626e-04, -1.10776164e-03,  6.04476118e-05,
        5.41223446e-04,  8.22050672e-04, -1.11630326e-03,  1.23393268e-03,
        7.71093037e-05, -1.33221620e-03,  1.44125230e-03,  3.58669786e-04,
       -4.37559705e-04,  3.73872404e-04, -7.00442470e-04,  1.09244417e-03,
       -3.80656915e-04, -1.48869934e-03,  4.96356864e-04, -5.51373174e-04,
        1.44536200e-04, -1.26706366e-03,  1.04345917e-03,  5.64948050e-06,
        1.37335598e-03, -2.21128503e-04,  1.49910769e-03, -3.68522858e-04,
        1.47571685e-04,  1.46835169e-03, -3.55020486e-04,  1.45661493e-03,
        8.75609112e-04,  4.92144551e-04,  4.29084757e-04,  4.28368367e-04,
       -1.14836043e-03,  1.04011176e-03,  5.34316350e-04, -4.28880012e-04,
       -8.06600205e-04, -1.14457950e-03,  1.21095206e-03,  2.19715395e-04,
       -1.14458776e-03, -2.74394726e-04,  2.39475034e-04,  1.52985347e-04,
        7.16696901e-04, -5.62688452e-04, -1.26933865e-03,  4.13507514e-04,
       -1.23335165e-03,  1.16435310e-03,  1.36969471e-03,  6.91420064e-05,
       -1.47546746e-03, -1.15285558e-03,  6.35192322e-04, -1.00481615e-03,
       -1.45432469e-03,  1.23785494e-03,  5.52299389e-05,  6.10006624e-04,
       -1.03039131e-03, -3.73000978e-04, -1.02684088e-03,  1.67118167e-04,
        1.17948166e-05, -5.52804449e-05, -1.03345443e-03, -1.57687959e-04,
       -9.41451115e-04, -2.85143207e-04, -1.47390494e-03,  4.20564262e-04,
        1.22658198e-03,  4.04714228e-04, -3.93306516e-04,  8.29581579e-04,
        1.29876353e-04,  8.98370519e-04, -9.69137007e-04,  5.60788554e-04,
       -7.57728121e-04, -1.51095958e-03,  8.37972271e-04, -9.56008560e-04,
       -1.91783896e-04,  1.43486261e-03, -6.06325688e-04,  1.26833050e-03,
       -1.16593926e-03, -4.21718491e-04,  8.50986922e-04,  1.23445131e-03,
       -1.09461625e-03,  1.90245220e-04,  1.04665500e-03,  5.54084720e-04,
       -6.55726239e-04, -1.17814692e-03,  6.81650592e-04,  1.50335210e-04,
       -1.04888726e-03,  1.82270174e-04,  9.98300384e-04, -1.73572000e-04,
        2.78131949e-04, -1.39944640e-03, -5.19407040e-04, -1.59195552e-04,
        1.21019722e-03, -1.16348802e-03, -4.20470111e-04, -9.89535329e-05,
        1.46995694e-03, -1.49615854e-03, -4.26641898e-04, -7.02133344e-04,
       -2.96182989e-04], dtype=float32)

In [ ]:
%%time
for epoch in range(EPOCHS):
    model_dbow.train(utils.shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dbow.alpha -= 0.002
    model_dbow.min_alpha = model_dbow.alpha

100%|██████████| 1750/1750 [00:00<00:00, 2258471.38it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2290181.59it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1212627.13it/s]
100%|██████████| 1750/1750 [00:00<00:00, 481345.14it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2382353.78it/s]
100%|██████████| 1750/1750 [00:00<00:00, 438603.65it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1247880.31it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2286614.33it/s]
100%|██████████| 1750/1750 [00:00<00:00, 994584.28it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1319437.71it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2295912.42it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1790688.46it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1167122.28it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2183233.79it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1361029.48it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1796825.46it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2474724.21it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1416174.42it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1250857.53it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1148315.39it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1335765.61it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1337713.14it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1277638.29it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1899102.72it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1354499.35it/s]

CPU times: user 21.3 s, sys: 784 ms, total: 22.1 s
Wall time: 13.6 s

In [ ]:
def vec_for_learning(model, tagged_docs):
    sents = tagged_docs.values
    targets, regressors = zip(*[(doc.tags[0], model.infer_vector(doc.words,alpha=0.065)) for doc in sents])
    return targets, regressors

In [ ]:
y_train, X_train = vec_for_learning(model_dbow, train_tagged)
y_test, X_test = vec_for_learning(model_dbow, test_tagged)

logreg = LogisticRegression(n_jobs=1, C=1e10,max_iter=30000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

from sklearn.metrics import accuracy_score, f1_score

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.6826666666666666
Testing F1 score: 0.6780200603718111

In [ ]:
model_dmm = Doc2Vec(dm=1, dm_mean=1, vector_size=VECTOR_SIZE, negative=5, window=WINDOW, min_count=2, workers=5, alpha=0.065, min_alpha=0.065)
model_dmm.build_vocab([x for x in tqdm(train_tagged.values)])

100%|██████████| 1750/1750 [00:00<00:00, 495814.10it/s]

In [ ]:
%%time
for epoch in range(EPOCHS):
    model_dmm.train(utils.shuffle([x for x in tqdm(train_tagged.values)]), total_examples=len(train_tagged.values), epochs=1)
    model_dmm.alpha -= 0.002
    model_dmm.min_alpha = model_dmm.alpha

100%|██████████| 1750/1750 [00:00<00:00, 1084199.70it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2378493.84it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1111620.78it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2373878.40it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2394790.21it/s]
100%|██████████| 1750/1750 [00:00<00:00, 388197.17it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2365463.10it/s]
100%|██████████| 1750/1750 [00:00<00:00, 371628.37it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1282549.71it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1709369.35it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2491524.78it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2310365.75it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1297972.06it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1345807.11it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1153548.95it/s]
100%|██████████| 1750/1750 [00:00<00:00, 999187.59it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2376183.88it/s]
100%|██████████| 1750/1750 [00:00<00:00, 859589.18it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1129235.69it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1240708.59it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1221506.41it/s]
100%|██████████| 1750/1750 [00:00<00:00, 2433697.61it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1732365.35it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1235071.85it/s]
100%|██████████| 1750/1750 [00:00<00:00, 1314711.09it/s]

CPU times: user 41.3 s, sys: 1.4 s, total: 42.7 s
Wall time: 23.7 s

In [ ]:
y_train, X_train = vec_for_learning(model_dmm, train_tagged)
y_test, X_test = vec_for_learning(model_dmm, test_tagged)
logreg1 = LogisticRegression(n_jobs=1, C=1e10,max_iter=30000)
logreg1.fit(X_train, y_train)
y_pred = logreg1.predict(X_test)
print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.23066666666666666
Testing F1 score: 0.23217804528287378

In [ ]:
# from gensim.test.test_doc2vec import ConcatenatedDoc2Vec
class ConcatenatedDocvecs(object):
    def __init__(self, models):
        self.models = models

    def __getitem__(self, token):
        return np.concatenate([model[token] for model in self.models])

class ConcatenatedDoc2Vec(object):
    """
    Concatenation of multiple models for reproducing the Paragraph Vectors paper.
    Models must have exactly-matching vocabulary and document IDs. (Models should
    be trained separately; this wrapper just returns concatenated results.)
    """

    def __init__(self, models):
        self.models = models
        if hasattr(models[0], 'docvecs'):
            self.docvecs = ConcatenatedDocvecs([model.docvecs for model in models])

    def __getitem__(self, token):
        return np.concatenate([model[token] for model in self.models])

    def infer_vector(self, document, alpha=0.065, min_alpha=0.065, steps=20):
        return np.concatenate([model.infer_vector(document, alpha, min_alpha, steps) for model in self.models])

    def train(self, *ignore_args, **ignore_kwargs):
        pass  # train subcomponents individually

new_model = ConcatenatedDoc2Vec([model_dbow, model_dmm])

In [ ]:
y_train, X_train = vec_for_learning(new_model, train_tagged)
y_test, X_test = vec_for_learning(new_model, test_tagged)
logreg2 = LogisticRegression(n_jobs=1, C=1e10,max_iter=30000)
logreg2.fit(X_train, y_train)
y_pred = logreg2.predict(X_test)
print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.724
Testing F1 score: 0.7121643078554772

In [ ]:
# temprory use
# y_test = np.asarray(y_test)

# matchedJdsindexList = []

# for i, _ in np.ndenumerate(y_test):
#   if y_test[i]==y_pred[i]:
#     matchedJdsindexList.append(i[0])


# # importing random module
# import random

# for idx in random.sample(matchedJdsindexList, 10):
#   print('jd number :',idx+2)
#   print('\n')
#   print('title')
#   print(jdDataSet['title'][idx])
#   print('\n')
#   print('description')
#   print(jdDataSet['description'][idx])
#   print('\n')
#   print('skills')
#   print(jdDataSet['skills'][idx])
#   print('--------------------------------------------------')

In [ ]:
# "Support Vector Classifier"
  
clf = SVC(kernel='linear') 

# fitting x samples and y classes 
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.6573333333333333
Testing F1 score: 0.6571954458808409

In [ ]:
lastModel = Pipeline([('Normalizing',MinMaxScaler()),('MultinomialNB',MultinomialNB())])
lastModel.fit(X_train, y_train)
prediction = lastModel.predict(X_test)

print('Testing accuracy %s' % accuracy_score(y_test, prediction))
print('Testing F1 score: {}'.format(f1_score(y_test, prediction, average='weighted')))

Testing accuracy 0.732
Testing F1 score: 0.7348299661192038

In [ ]:
clf2 = SVC(kernel='poly', degree=2,probability=True)
clf2.fit(X_train, y_train)

y_pred = clf2.predict(X_test)

print('Testing accuracy %s' % accuracy_score(y_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(y_test, y_pred, average='weighted')))

Testing accuracy 0.5573333333333333
Testing F1 score: 0.5821594632090771